spring:
  application:
    name: eureka-consumer-feign-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 9003
#开启熔断器
feign:
  hystrix:
    enabled: true
#监控单实例节点endpoint，Hystrix Dashboard 监控单实例节点需要通过访问实例的/actuator/hystrix.stream接口来实现
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
